project:
  type: book

book:
  title: "Das souveräne Individuum"
  subtitle: "Der Übergang zum Informationszeitalter"
  author: "James Dale Davidson & Lord William Rees-Mogg"
  translator: Andreas Tank
  date: "9/10/2024"
  cover-image: cover.png
  isbn: 978-3-16-123450-0
  license: CC-BY-4.0
  language: de
  original-title: "The Sovereign Individual"
  publisher: Konsensus Network
  navbar:
    logo: cover.png
    logo-alt: Cover
    right:
      - icon: github
        href: https://github.com/konsensusnetwork/TSI_DE
        aria-label: GitHub
      - icon: shop
        href: https://bitcoinbook.shop/
        aria-label: Shop
  page-footer:
    center:
      - text: "License"
        href: index.qmd
  open-graph: true
  twitter-card:
    site: "@konsensusn"
  chapters:
    - index.qmd
    - chapters/TSI_DE_CH01.qmd
    - chapters/TSI_DE_CH02.qmd
    - chapters/TSI_DE_CH03.qmd
    - chapters/TSI_DE_CH04.qmd
    - chapters/TSI_DE_CH05.qmd
    - chapters/TSI_DE_CH06.qmd
    - chapters/TSI_DE_CH07.qmd
    - chapters/TSI_DE_CH08.qmd
    - chapters/TSI_DE_CH09.qmd
    - chapters/TSI_DE_CH10.qmd
    - chapters/TSI_DE_CH11.qmd

format:
  html:
    theme: cosmo
    number-depth: 1
    reader-mode: true
  latex:
    documentclass: memoir
    classoption: smalldemyvopaper,11pt,twoside,onecolumn,openright,extrafontsizes
    papersize: a5
    secnumdepth: 1
    geometry:
      - top=18mm
      - bottom=28mm
      - left=18mm
      - right=18mm
  epub:
    creator: Konsensus Network



